name: Run tox jobs

on:
  - push
  - pull_request

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install tox
    - name: Run lint jobs
      run: tox -e linters
    - name: Run unit tests
      run: tox -e py3
